// <auto-generated />
using System;
using CapstoneProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapstoneProject.Migrations
{
    [DbContext(typeof(CapstoneProjectDbContext))]
    [Migration("20260421161503_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapstoneProject.Areas.Identity.Data.CapstoneProjectUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AttendsCherokee")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendsDowntown")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendsSpartanburg")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendsTygerRiver")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendsUnion")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Employed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("EmployedHouseMembers")
                        .HasColumnType("tinyint");

                    b.Property<bool>("EthAfricanAmerican")
                        .HasColumnType("bit");

                    b.Property<bool>("EthAsian")
                        .HasColumnType("bit");

                    b.Property<bool>("EthCaucasian")
                        .HasColumnType("bit");

                    b.Property<bool>("EthLatino")
                        .HasColumnType("bit");

                    b.Property<bool>("EthMiddleEastern")
                        .HasColumnType("bit");

                    b.Property<bool>("EthNativeAmerican")
                        .HasColumnType("bit");

                    b.Property<bool>("EthOther")
                        .HasColumnType("bit");

                    b.Property<bool>("EthPacificIslander")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSNAP")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTANF")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasTransportation")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWIC")
                        .HasColumnType("bit");

                    b.Property<byte>("HouseholdAdults")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HouseholdBabiesChildren")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HouseholdBabiesToddlers")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HouseholdTeens")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsInterestedInSNAP")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInterestedInTANF")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInterestedInWIC")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRegistrationComplete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("StudentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CapstoneProject.Models.Donation", b =>
                {
                    b.Property<int>("DonationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationID"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DonationID");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("CapstoneProject.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointCost")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("SubcategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.HasIndex("SubcategoryID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Description = "Gallon of Whole milk",
                            PointCost = 5,
                            Quantity = 1m,
                            SubcategoryID = 1,
                            Type = "Gallon-Whole",
                            UUID = "62446e0b-b4a2-4430-93e9-edcee1007375"
                        },
                        new
                        {
                            ItemID = 2,
                            Description = "Aged cheddar cheese",
                            PointCost = 7,
                            Quantity = 2.5m,
                            SubcategoryID = 2,
                            Type = "Cheddar",
                            UUID = "532026ed-b264-44e7-81a6-abd2007ffeaf"
                        },
                        new
                        {
                            ItemID = 3,
                            Description = "Greek yogurt",
                            PointCost = 3,
                            Quantity = 1m,
                            SubcategoryID = 3,
                            Type = "Greek",
                            UUID = "fcfe3fd1-d10e-4b0f-8d98-ddf2fdfa6663"
                        },
                        new
                        {
                            ItemID = 4,
                            Description = "Fresh red apples",
                            PointCost = 2,
                            Quantity = 3m,
                            SubcategoryID = 5,
                            Type = "Apple",
                            UUID = "e94a0402-f2f9-40e2-b423-7b8e4c65be5d"
                        },
                        new
                        {
                            ItemID = 5,
                            Description = "Carrots",
                            PointCost = 1,
                            Quantity = 5.0m,
                            SubcategoryID = 6,
                            Type = "Carrot",
                            UUID = "97255123-ddc5-4cc4-8a3a-aa3a65809356"
                        },
                        new
                        {
                            ItemID = 6,
                            Description = "Canned Spam",
                            PointCost = 6,
                            Quantity = 12.0m,
                            SubcategoryID = 7,
                            Type = "Spam",
                            UUID = "4622ef7d-72fe-4db8-8182-056d02da6cdf"
                        },
                        new
                        {
                            ItemID = 7,
                            Description = "Canned tomato soup",
                            PointCost = 3,
                            Quantity = 8.0m,
                            SubcategoryID = 9,
                            Type = "Tomato Soup",
                            UUID = "a89ea68b-4b7a-4651-a150-ac534ddc81ae"
                        },
                        new
                        {
                            ItemID = 8,
                            Description = "Box of spaghetti pasta",
                            PointCost = 2,
                            Quantity = 1.0m,
                            SubcategoryID = 11,
                            Type = "Spaghetti",
                            UUID = "04368fd1-c129-4e1c-98c2-c4d058d713f9"
                        },
                        new
                        {
                            ItemID = 9,
                            Description = "Premium basmati rice",
                            PointCost = 5,
                            Quantity = 2.0m,
                            SubcategoryID = 12,
                            Type = "Basmati",
                            UUID = "7b5caca6-d148-4966-8163-2211c9545f1a"
                        });
                });

            modelBuilder.Entity("CapstoneProject.Models.ItemCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("ItemCategories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Dairy"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Produce"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "Canned Products"
                        },
                        new
                        {
                            CategoryID = 4,
                            Name = "Grains/Pasta"
                        },
                        new
                        {
                            CategoryID = 5,
                            Name = "Laundry"
                        },
                        new
                        {
                            CategoryID = 6,
                            Name = "Personal Care"
                        },
                        new
                        {
                            CategoryID = 7,
                            Name = "Baby Care"
                        });
                });

            modelBuilder.Entity("CapstoneProject.Models.ItemSubcategory", b =>
                {
                    b.Property<int>("SubcategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubcategoryID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ItemSubcategories");

                    b.HasData(
                        new
                        {
                            SubcategoryID = 1,
                            CategoryID = 1,
                            Name = "Milk"
                        },
                        new
                        {
                            SubcategoryID = 2,
                            CategoryID = 1,
                            Name = "Cheese"
                        },
                        new
                        {
                            SubcategoryID = 3,
                            CategoryID = 1,
                            Name = "Yogurt"
                        },
                        new
                        {
                            SubcategoryID = 4,
                            CategoryID = 1,
                            Name = "Butter"
                        },
                        new
                        {
                            SubcategoryID = 5,
                            CategoryID = 2,
                            Name = "Fruit"
                        },
                        new
                        {
                            SubcategoryID = 6,
                            CategoryID = 2,
                            Name = "Vegetable"
                        },
                        new
                        {
                            SubcategoryID = 7,
                            CategoryID = 3,
                            Name = "Canned Meat"
                        },
                        new
                        {
                            SubcategoryID = 8,
                            CategoryID = 3,
                            Name = "Canned Vegetable"
                        },
                        new
                        {
                            SubcategoryID = 9,
                            CategoryID = 3,
                            Name = "Other Can Food"
                        },
                        new
                        {
                            SubcategoryID = 10,
                            CategoryID = 4,
                            Name = "Bread"
                        },
                        new
                        {
                            SubcategoryID = 11,
                            CategoryID = 4,
                            Name = "Box Pasta"
                        },
                        new
                        {
                            SubcategoryID = 12,
                            CategoryID = 4,
                            Name = "Rice"
                        },
                        new
                        {
                            SubcategoryID = 13,
                            CategoryID = 4,
                            Name = "Other Grains"
                        },
                        new
                        {
                            SubcategoryID = 14,
                            CategoryID = 5,
                            Name = "Liquid Detergent"
                        },
                        new
                        {
                            SubcategoryID = 15,
                            CategoryID = 5,
                            Name = "Dry Detergent"
                        },
                        new
                        {
                            SubcategoryID = 16,
                            CategoryID = 5,
                            Name = "Bleach"
                        },
                        new
                        {
                            SubcategoryID = 17,
                            CategoryID = 5,
                            Name = "Other Laundry"
                        },
                        new
                        {
                            SubcategoryID = 18,
                            CategoryID = 6,
                            Name = "Body Soap"
                        },
                        new
                        {
                            SubcategoryID = 19,
                            CategoryID = 6,
                            Name = "Shampoo"
                        },
                        new
                        {
                            SubcategoryID = 20,
                            CategoryID = 6,
                            Name = "Conditioner"
                        },
                        new
                        {
                            SubcategoryID = 21,
                            CategoryID = 6,
                            Name = "Toothpaste"
                        },
                        new
                        {
                            SubcategoryID = 22,
                            CategoryID = 6,
                            Name = "Hand Soap"
                        },
                        new
                        {
                            SubcategoryID = 23,
                            CategoryID = 6,
                            Name = "Deodorant"
                        },
                        new
                        {
                            SubcategoryID = 24,
                            CategoryID = 7,
                            Name = "Diapers"
                        },
                        new
                        {
                            SubcategoryID = 25,
                            CategoryID = 7,
                            Name = "Wipes"
                        },
                        new
                        {
                            SubcategoryID = 26,
                            CategoryID = 7,
                            Name = "Lotion"
                        },
                        new
                        {
                            SubcategoryID = 27,
                            CategoryID = 7,
                            Name = "Shampoo"
                        },
                        new
                        {
                            SubcategoryID = 28,
                            CategoryID = 7,
                            Name = "Powder"
                        });
                });

            modelBuilder.Entity("CapstoneProject.Models.Liability", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RenewalDate")
                        .HasColumnType("date");

                    b.HasKey("UserID");

                    b.ToTable("LiabilityForms");
                });

            modelBuilder.Entity("CapstoneProject.Models.Purchasing", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseID"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopTransactionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("CapstoneProject.Models.ResourceRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BeanCanned")
                        .HasColumnType("bit");

                    b.Property<bool>("BeanDry")
                        .HasColumnType("bit");

                    b.Property<bool>("BoxMealBeef")
                        .HasColumnType("bit");

                    b.Property<bool>("BoxMealChicken")
                        .HasColumnType("bit");

                    b.Property<bool>("BoxMealOther")
                        .HasColumnType("bit");

                    b.Property<bool>("BoxMealVegetarian")
                        .HasColumnType("bit");

                    b.Property<bool>("CanMeatOther")
                        .HasColumnType("bit");

                    b.Property<bool>("CanMeatTuna")
                        .HasColumnType("bit");

                    b.Property<bool>("CanOpener")
                        .HasColumnType("bit");

                    b.Property<bool>("CanVegetableCarrot")
                        .HasColumnType("bit");

                    b.Property<bool>("CanVegetableCorn")
                        .HasColumnType("bit");

                    b.Property<bool>("CanVegetableGreenBean")
                        .HasColumnType("bit");

                    b.Property<bool>("CanVegetableMix")
                        .HasColumnType("bit");

                    b.Property<bool>("CanVegetableOther")
                        .HasColumnType("bit");

                    b.Property<bool>("CanVegetablePeas")
                        .HasColumnType("bit");

                    b.Property<bool>("CanVegetableTomato")
                        .HasColumnType("bit");

                    b.Property<bool>("CerealBreakfastBar")
                        .HasColumnType("bit");

                    b.Property<bool>("CerealKids")
                        .HasColumnType("bit");

                    b.Property<bool>("CerealOatmeal")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DietaryRestrictions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("HouseholdAdults")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HouseholdUnderage")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Microwave")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherCannedFruit")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherJelly")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherMacNCheese")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherMashedPotatoe")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherPastaAndSauce")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherPeanutButter")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherRice")
                        .HasColumnType("bit");

                    b.Property<bool>("Oven")
                        .HasColumnType("bit");

                    b.Property<bool>("RamenBeef")
                        .HasColumnType("bit");

                    b.Property<bool>("RamenChicken")
                        .HasColumnType("bit");

                    b.Property<bool>("RamenOther")
                        .HasColumnType("bit");

                    b.Property<bool>("RamenPork")
                        .HasColumnType("bit");

                    b.Property<bool>("RamenShrimp")
                        .HasColumnType("bit");

                    b.Property<bool>("RamenVegetable")
                        .HasColumnType("bit");

                    b.Property<bool>("RunningWater")
                        .HasColumnType("bit");

                    b.Property<bool>("SnackChips")
                        .HasColumnType("bit");

                    b.Property<bool>("SnackCrackers")
                        .HasColumnType("bit");

                    b.Property<bool>("SnackGranolaBar")
                        .HasColumnType("bit");

                    b.Property<bool>("SnackOther")
                        .HasColumnType("bit");

                    b.Property<bool>("SoupChicken")
                        .HasColumnType("bit");

                    b.Property<bool>("SoupChili")
                        .HasColumnType("bit");

                    b.Property<bool>("SoupCream")
                        .HasColumnType("bit");

                    b.Property<bool>("SoupOther")
                        .HasColumnType("bit");

                    b.Property<bool>("SoupTomato")
                        .HasColumnType("bit");

                    b.Property<bool>("SoupVegetable")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stove")
                        .HasColumnType("bit");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestID");

                    b.ToTable("ResourceRequests");
                });

            modelBuilder.Entity("CapstoneProject.Models.StaffRegister", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("StaffRegisters");
                });

            modelBuilder.Entity("CapstoneProject.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int>("AdditionalPointCost")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialRequests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CapstoneProject.Models.TransactionLineItem", b =>
                {
                    b.Property<int>("TransactionID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPAL")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRG")
                        .HasColumnType("bit");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionID", "ItemID");

                    b.HasIndex("ItemID");

                    b.ToTable("TransactionLineItems");
                });

            modelBuilder.Entity("CapstoneProject.Models.UserSurvey", b =>
                {
                    b.Property<int>("SurveyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyID"));

                    b.Property<string>("AllocateFunds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssistanceReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampusStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassActivities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassAttendance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreqFoodInadequate")
                        .HasColumnType("bit");

                    b.Property<string>("FreqServices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedOpinion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotEnoughFood")
                        .HasColumnType("bit");

                    b.Property<string>("PantryPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RecievedDairy")
                        .HasColumnType("bit");

                    b.Property<bool>("RecievedFruit")
                        .HasColumnType("bit");

                    b.Property<bool>("RecievedGrains")
                        .HasColumnType("bit");

                    b.Property<bool>("RecievedOther")
                        .HasColumnType("bit");

                    b.Property<bool>("RecievedPersonalCare")
                        .HasColumnType("bit");

                    b.Property<bool>("RecievedProtein")
                        .HasColumnType("bit");

                    b.Property<bool>("RecievedVegetables")
                        .HasColumnType("bit");

                    b.Property<string>("SkipMeal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TurnedAwayMoney")
                        .HasColumnType("bit");

                    b.Property<bool>("TurnedAwayNo")
                        .HasColumnType("bit");

                    b.Property<bool>("TurnedAwayOther")
                        .HasColumnType("bit");

                    b.Property<bool>("TurnedAwayStudent")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedOtherPantries")
                        .HasColumnType("bit");

                    b.Property<string>("UserClassYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCustService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEnrolled")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserGrades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserJobEmployed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserJobPerformance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserOpinionComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserOpinionImprove")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserOpinionProducts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserOpinionServices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurveyID");

                    b.ToTable("UserSurveys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CapstoneProject.Models.Item", b =>
                {
                    b.HasOne("CapstoneProject.Models.ItemSubcategory", "ItemSubcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemSubcategory");
                });

            modelBuilder.Entity("CapstoneProject.Models.ItemSubcategory", b =>
                {
                    b.HasOne("CapstoneProject.Models.ItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CapstoneProject.Models.TransactionLineItem", b =>
                {
                    b.HasOne("CapstoneProject.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProject.Models.Transaction", null)
                        .WithMany("LineItems")
                        .HasForeignKey("TransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CapstoneProject.Areas.Identity.Data.CapstoneProjectUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CapstoneProject.Areas.Identity.Data.CapstoneProjectUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProject.Areas.Identity.Data.CapstoneProjectUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CapstoneProject.Areas.Identity.Data.CapstoneProjectUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapstoneProject.Models.Transaction", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
